trigger:
  - master

pr: none

pool:
  vmImage: 'macos-latest'

variables:
  - group: aps-ios
  - group: git-credentials
  - group: source-clear-credentials
  - group: ios-signing
  - name: configuration
    value: 'Release'
  - name: sdk
    value: 'iphoneos'

steps:
- checkout: self

#- script: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
#  displayName: 'Installing Homebrew'

#- script: brew install fastlane
# displayName: 'Installing fastlane'

- task: CmdLine@2
  displayName: Adding Alfresco private podspec repository
  inputs:
    script: |
      pod repo add AlfrescoPodspec https://$(gitUser):$(gitPAT)@github.com/Alfresco/alfresco-private-podspecs-ios-sdk.git
- task: CmdLine@2
  displayName: Installing pods
  inputs:
    script: |
      pod install
- task: CmdLine@2
  displayName: Variable substitution for GoogleAnalytics
  inputs:
    script: 'plutil -replace API_KEY -string $(GA_API_KEY) GoogleService-Info.plist'
    workingDirectory: '$(System.DefaultWorkingDirectory)/AlfrescoActiviti/'

- task: Xcode@5
  displayName: 'Running tests'
  inputs:
    actions: 'clean test'
    sdk: 'iphonesimulator'
    xcodeVersion: 11
    scheme: 'AlfrescoActiviti'
    configuration: 'Debug'
    destinationPlatformOption: 'custom'
    destinationPlatform: 'iOS'
    destinationSimulators: 'iPhone 11'
    xcWorkspacePath: '**/AlfrescoActiviti.xcworkspace'
    useXcpretty: true
    publishJUnitResults: 'build/reports/junit.xml'

- task: PublishTestResults@2
  displayName: 'Publish test'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'build/reports/junit.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Publishing test results'

- task: InstallAppleCertificate@2
  inputs:
   certSecureFile: '$(p12FileName)'
   certPwd: '$(p12Password)'
   keychain: 'temp'
   deleteCert: true 

- task: InstallAppleProvisioningProfile@1
  inputs:
   provisioningProfileLocation: 'secureFiles'
   provProfileSecureFile: '$(apsReleaseProvisioningProfile)'
   removeProfile: true 

- task: CmdLine@2
  displayName: 'Increment build version'
  inputs:
    script: |
      fastlane run increment_build_number build_number:$(Build.BuildID)

- task: CmdLine@2
  displayName: 'Preparing IPA file for Testflight'
  inputs:
    script: |
      fastlane PrepareForTestFlight

- task: Xcode@5
  displayName: 'Archive Process Services App'
  inputs:
    actions: 'build archive'
    sdk: '$(sdk)'
    scheme: 'AlfrescoActiviti'
    configuration: '$(configuration)'
    xcWorkspacePath: '**/AlfrescoActiviti.xcworkspace'
    useXcpretty: 'false'
    args: '-archivePath $(agent.buildDirectory)/AlfrescoActiviti'

- task: ArchiveFiles@2
  displayName: 'Package .xcarchive into a zip file'
  inputs:
    rootFolderOrFile: '$(agent.buildDirectory)/AlfrescoActiviti.xcarchive/'
    archiveFile: '$(build.artifactStagingDirectory)/AlfrescoActiviti.xcarchive.zip'

- task: CopyFiles@2
  inputs:
    contents: '**/*.ipa'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)/AlfrescoActiviti.xcarchive.zip'
    artifactName: 'xcarchive-files'
    artifactType: 'container'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(build.artifactStagingDirectory)' 
    artifactName: 'APS-iOS' 
    publishLocation: 'Container'

- task: CmdLine@2
  inputs:
    script: 'curl -sSL https://download.sourceclear.com/ci.sh | sh'
  displayName: 'Performing Source Clear checks'
  env:
    SRCCLR_API_TOKEN: $(source_clear_token)

- task: AppStoreRelease@1
  inputs:
    serviceEndpoint: 'AppleStore Publisher'
    appIdentifier: 'com.alfresco.activiti'
    appType: 'iOS'
    ipaPath: '**/*.ipa'
    releaseTrack: 'TestFlight'
    shouldSkipWaitingForProcessing: true
    teamId: 'W8N95J537P'
    teamName: 'Alfresco Software, Inc.'