trigger:
  - master

pr: none

pool:
  vmImage: 'macos-latest'

variables:
  - group: aps-ios
  - group: git-credentials
  - group: source-clear-credentials
  - group: ios-signing
  - name: configuration
    value: 'Release'
  - name: sdk
    value: 'iphoneos'
  - name: cocoapods_path
    value: $(Pipeline.Workspace)/.cocoapods

steps:
- checkout: self

- task: Cache@2
  inputs:
    key: 'cocoapods | Podfile.lock'
    restoreKeys: cocoapods
    path: $(cocoapods_path)
  displayName: Cache CocoaPods Specs

- task: Cache@2
  inputs:
    key: 'pods | Podfile.lock'
    restoreKeys: pods
    path: Pods
  displayName: Cache Pods

- task: CmdLine@2
  displayName: 'Increment build version'
  inputs:
    script: |
      fastlane run increment_build_number build_number:$(Build.BuildID)

- task: CmdLine@2
  displayName: Installing pods
  inputs:
    script: |
      pod install
- task: CmdLine@2
  displayName: Variable substitution for GoogleAnalytics
  inputs:
    script: 'plutil -replace API_KEY -string $(GA_API_KEY) GoogleService-Info.plist'
    workingDirectory: '$(System.DefaultWorkingDirectory)/AlfrescoActiviti/'

- task: Xcode@5
  displayName: 'Running tests'
  inputs:
    actions: 'clean test'
    sdk: 'iphonesimulator'
    xcodeVersion: 12
    scheme: 'AlfrescoActiviti'
    configuration: 'Debug'
    destinationPlatformOption: 'custom'
    destinationPlatform: 'iOS'
    destinationSimulators: 'iPhone 12'
    xcWorkspacePath: '**/AlfrescoActiviti.xcworkspace'
    useXcpretty: true
    publishJUnitResults: 'build/reports/junit.xml'

- task: PublishTestResults@2
  displayName: 'Publish test'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'build/reports/junit.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Publishing test results'

- task: InstallAppleCertificate@2
  inputs:
   certSecureFile: '$(p12FileName)'
   certPwd: '$(p12Password)'
   keychain: 'temp'
   deleteCert: true

- task: InstallAppleProvisioningProfile@1
  inputs:
   provisioningProfileLocation: 'secureFiles'
   provProfileSecureFile: '$(provisioning_profile)'
   removeProfile: true

- task: DownloadSecureFile@1
  name: prov_profile
  inputs:
    secureFile: '$(provisioning_profile)'

- task: CmdLine@2
  displayName: 'Build and Pilot'
  inputs:
    script: 'bundle update && bundle exec fastlane build_and_pilot'
  env:
      FASTLANE_DISABLE_COLORS: 'true'
      FASTLANE_USER: $(appstore_upload_user)
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: $(appstore_upload_token)
      PROV_PROFILE: $(prov_profile.secureFilePath)
      SIGNING_IDENTITY: $(signing_identity)
      APPSTORE_APP_ID: $(appstore_app_id)
      CONFIGURATION: $(configuration)

- task: CmdLine@2
  inputs:
    script: 'curl -sSL https://download.sourceclear.com/ci.sh | sh'
  displayName: 'Performing Source Clear checks'
  env:
    SRCCLR_API_TOKEN: $(source_clear_token)