default_platform(:ios)
xcversion(version: "~> 12.0")

platform :ios do
  desc "Build and Pilot"
  lane :build_and_pilot do
      update_project_provisioning(
        xcodeproj: "AlfrescoActiviti.xcodeproj",
        profile: ENV["PROV_PROFILE"],
        target_filter: "AlfrescoActiviti",
        build_configuration: ENV["CONFIGURATION"],
        code_signing_identity: ENV["SIGNING_IDENTITY"]
      )
      build_app(
        scheme: "AlfrescoActiviti",
        configuration: ENV["CONFIGURATION"]
      )
      upload_to_testflight(
        skip_waiting_for_build_processing: true,
        apple_id: ENV["APPSTORE_APP_ID"]
      )
  end
end
